name: Tests

on:
    push:
        branches:
            - master
            - '*.x'
    pull_request:
    schedule:
        -   cron: '0 0 * * *'

jobs:
    linux_tests:
        name: PHP ${{ matrix.php }} - Linux
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.1, 8.2, 8.3, 8.4, 8.5 ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, fileinfo, mbstring
                    tools: composer:v2
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --prefer-dist

            -   name: Run tests
                run: vendor/bin/phpunit --coverage-clover coverage.xml

            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}

    windows_tests:
        name: PHP ${{ matrix.php }} - Windows
        runs-on: windows-2022

        strategy:
            fail-fast: false
            matrix:
                php: [ 8.1, 8.2, 8.3, 8.4, 8.5 ]

        steps:
            -   name: Set git to use LF
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, fileinfo, mbstring
                    tools: composer:v2

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --prefer-dist

            -   name: Run tests
                run: vendor/bin/phpunit
